[workspace]
channels = ["conda-forge"]
name = "seabreeze-gui"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.2,<3"
pyqtgraph = ">=0.13.7,<0.14"
seabreeze = ">=2.10.1,<3"
pyqt = ">=5.15.11,<6"

[pypi-dependencies]
seatease = ">=0.4.0, <0.5"
